- type: gameMapPool
  id: DefaultMapPool
  maps:
  - Atlas
  - Bagel
  - Box
  - Cluster
  - Core
  - Fland
  - Marathon
  - Meta
  - Omega
  - Origin
  - Saltern
  - Packed
  - Reach
  - trieste
  #- Train <- return after station anchoring PR is finished and merged
