- type: job
  id: Pilot
  name: job-name-pilot
  description: job-description-pilot
  playTimeTracker: JobSalvageSpecialist
  requirements:
    - !type:DepartmentTimeRequirement
      department: Expeditionary
      time: 3600 # 1 hr
  icon: "JobIconShaftMiner"
  startingGear: PilotGear
  supervisors: job-supervisors-qm
  access:
  - Salvage
  - Maintenance
  - External

- type: startingGear
  id: PilotGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitMercenary
    id: PilotPDA
    ears: ClothingHeadsetCargo
    outerClothing: ClothingOuterCoatBomber
    gloves: ClothingHandsGlovesFingerless
    head: ClothingHeadHatHardhatArmored # protect the pilot
